status = error
name = Log4j2Config

# Console Appender
appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d [%t] %-5level %logger - %msg%n

# File Appender
appender.file.type = File
appender.file.name = FileAppender
appender.file.fileName = logs/automation.log
appender.file.layout.type = PatternLayout
appender.file.layout.pattern = %d [%t] %-5level %logger - %msg%n
appender.file.append= true

# Root Logger
rootLogger.level = info
rootLogger.appenderRefs = console, file
rootLogger.appenderRef.console.ref = ConsoleAppender
rootLogger.appenderRef.file.ref = FileAppender